### ISSUE TITLE
When calculating arbitrage, it should compare BID & ASK

### ISSUE THREAD

**Issue by agustinf** [psaratscheff/ether-monitor#1]
We can see here https://github.com/psaratscheff/ether-monitor/blob/master/controllers/arbitrageCtrl.js#L67 that to determine an arbitrage opportunity the bot is comparing local BID/ASK with an average international price. 

I think we should compare the maximum BID of one exchange with the minimum ASK on the other exchange and vice versa. When the local maximum BID is higher than the minimum ASK on the other exchange, I can sell over there and buy over here.

**Comment by saratscheff** [comment]
Fully agree! When this code was written, no API was found for [Lykke](https://www.lykke.com) (The exchange being used at the moment). But now: https://api.lykkex.com/swagger/ui/index/index.html 
Also, support for [Kraken](https://www.kraken.com) should be considered: https://www.kraken.com/help/api

Definitely putting both implementations on the roadmap.

**Comment by saratscheff** [comment]
Fixed: ec6b3bf4126f63f795096a08424be44f4fa8af73
